#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -merge $HOME/.Xresources

bspc monitor HDMI-1 -d 1 2 3 4
bspc monitor eDP-1 -d 5 6 7 8

#run xrandr command if external monitor is connected
if [ -x $HOME/bin/own_script_bspwm_laptop_dual_monitor ];then
    own_script_bspwm_laptop_dual_monitor
fi

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/local/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# AutoStart
picom &
feh --bg-fill ~/Pictures/slide/wallpaper1.jpeg
$HOME/.config/polybar/launch.sh

